OCC startup (istep 21.1)
3mdeb/coreboot pull request #100
Opened 2021-09-24 22:28 UTC by SergiiDmytruk

Includes #89.

2021-10-11 15:31 UTC, krystian-hebel requested changes

2021-10-11 15:31 UTC, krystian-hebel commented on src/include/cpu/power/occ.h
> +#define BRANCH_ADDR_MASK (0x00FFFFFC)
These are wrong, should be 0x48000002 and 0x03FFFFFC respectively, this error was copied from Hostboot. Nonetheless, it is not actually used so can be removed.

2021-10-11 15:31 UTC, krystian-hebel commented on src/include/cpu/power/occ.h
> +};
There are 12 EXs, which are accessed through quad chiplets. Names are misleading, as well as use of this table in clear_occ_special_wakeups() - see comment there.

2021-10-11 15:31 UTC, krystian-hebel commented on src/include/cpu/power/occ.h
> +uint64_t makeStart405Instruction(void);
Unused, please remove.

2021-10-11 15:31 UTC, krystian-hebel commented on src/include/cpu/power/occ.h
> +};
AFAICT only OCB0 is ever used, drop these tables and use appropriate register directly.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/Makefile.inc
> +romstage-y += occ.c
Why is it needed for romstage?

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/occ.c
> +    }
As mentioned in the header, there are 12 EXs, which are accessed through even core chiplets. This loop should be something like this:

```
for (size_t chiplet_index = 0; chiplet_index < MAX_CORES /* 24 */; chiplet_index += 2) {
    write_scom_for_chiplet(EP00_CHIPLET_ID + chiplet_index, EX_PPM_SPWKUP_OCC, ....
}
```
or
```
for (size_t ex_index = 0; ex_index < MAX_EXS /* 12 */; ++ex_index) {
    write_scom_for_chiplet(EP00_CHIPLET_ID + ex_index * 2, EX_PPM_SPWKUP_OCC, ....
}
```

2021-10-11 15:31 UTC, krystian-hebel commented on src/include/cpu/power/occ.h
> +};
Also, if any register address is not needed outside of occ.c, move its definition there.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	write_scom_direct(PBA_BARMSKs[index], 0x300000);
According to dumps, this is 8M for BAR2 (0x700000). This is also set [here](https://github.com/3mdeb/coreboot/blob/a11f8a632a089c3de818f467f6d6abc658222588/src/soc/ibm/power9/homer.c#L2128) - one of these should be enough.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	uint8_t *common_area = (uint8_t *)homer + sizeof(*homer);
Hostboot reserves memory for 8 HOMER images (4M each) and one common area (8M) after the last one. For Talos we will need two HOMERs when second CPU is installed, so it shouldn't be hardcoded. Second CPU will also use different address of HOMER, but the same common area, so for now it will be enough to just pass pointer to common_area to load_pm_complex() and hardcode it at the highest possible level.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	/* XXX: how come this points into padding area? */
This explains last unaccounted differences between our HOMER and one prepared by Hostboot somewhere after 15.2

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	}
Is it supposed to work on cores, and not EXs as clear_occ_special_wakeups() did? I don't see this in dumps at all.

The final read is some kind of workaround? If yes, please add a comment.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	write_scom(OCBCSRn_OR[0], PPC_BIT(OCB_PIB_OCBCSR0_OCB_STREAM_MODE));
Use `PU_OCB_PIB_OCBCSR0_OR` directly.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/occ.c
> +    write_scom(OCBARn[0], (uint64_t)i_ocb_bar << 32);
If this is always for OCB0, use register names directly.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/occ.c
> +            wait_us(1, false);
Does it work without this delay? Maybe it was used for simulation only.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/occ.c
> +}
Unused, please remove.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	enum { MTSPR_CONST1 = 467 };
Maybe use 0x7C0003A6 as MTSPR_OP and drop this? This is extended opcode, without it instruction isn't `mtspr` anyway.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	enum { BCCTR_CONST1 = 528 };
Same as above.

2021-10-11 15:31 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	inst = BR_OP << (31 - 5);
BR_OP is already shifted, so:
```suggestion
	inst = BR_OP;
```
No idea why it works in this form...

2021-10-11 16:23 UTC, SergiiDmytruk commented on src/soc/ibm/power9/Makefile.inc
> +romstage-y += occ.c
This is from #89, I removed this line in a later commit.

2021-10-11 16:31 UTC, SergiiDmytruk commented on src/soc/ibm/power9/occ.c
> +            wait_us(1, false);
Haven't tried without the delay, will test. I'm surprised it works at all... bits are checked with `& bit_pos` instead of `& PPC_BIT(bit_pos)`. Haven't looked at it closely before.

2021-10-11 16:58 UTC, SergiiDmytruk commented on src/soc/ibm/power9/homer.c
> +	inst = BR_OP << (31 - 5);
This is from an old commit.

2021-10-11 17:02 UTC, SergiiDmytruk commented on src/include/cpu/power/occ.h
> +};
Moved more stuff to `occ.c`, which simplified things. I was just expecting #89 to be merged first and avoided modifying `occ.c` too much.

2021-10-11 19:15 UTC, SergiiDmytruk commented on src/soc/ibm/power9/homer.c
> +	}
I probably did iteration over cores because they are used for computing address in `src/import/chips/p9/procedures/hwp/pm/p9_cpu_special_wakeup_ex.C` (code related to wakeups is rather convoluted) and logs have this as if they iterate over cores as well:
```
553.73054|SCAN|TRACE : PUTSCOM     :  pu:k0:n0:s0:p00 : 00000000210F010B 0000000000000000
553.73056|SCAN|TRACE : GETSCOM     :  pu:k0:n0:s0:p00 : 00000000210F010B 0000000000000000

553.73084|SCAN|TRACE : PUTSCOM     :  pu:k0:n0:s0:p00 : 00000000230F010B 0000000000000000
553.73086|SCAN|TRACE : GETSCOM     :  pu:k0:n0:s0:p00 : 00000000230F010B 0000000000000000

553.73114|SCAN|TRACE : PUTSCOM     :  pu:k0:n0:s0:p00 : 00000000240F010B 0000000000000000
553.73116|SCAN|TRACE : GETSCOM     :  pu:k0:n0:s0:p00 : 00000000240F010B 0000000000000000

553.73145|SCAN|TRACE : PUTSCOM     :  pu:k0:n0:s0:p00 : 00000000270F010B 0000000000000000
553.73147|SCAN|TRACE : GETSCOM     :  pu:k0:n0:s0:p00 : 00000000270F010B 0000000000000000
```
Hostboot seems to send wakeup to functional core of an EX instead of the first one.

Final read adds a delay, copied comment from Hostboot.

2021-10-11 20:52 UTC, SergiiDmytruk commented on src/soc/ibm/power9/occ.c
> +            wait_us(1, false);
Removed the delay. Seems to make no difference.

2021-10-12 06:20 UTC, krystian-hebel commented on src/soc/ibm/power9/Makefile.inc
> +romstage-y += occ.c
Huh, I have no idea how but I managed to review older version, sorry about that.

2021-10-12 08:36 UTC, krystian-hebel requested changes

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +		write_scom_for_chiplet(quad_chiplet, EQ_QPPM_QPMMR_CLEAR, 0xfffe3aa000000000ull);
Here and for all other SCOMs: I'd rather see PPC_BIT(MASK) macros used for this, as long as we know the layout of the register. That way it is easier to understand and check if code does what comment says without manually counting bit positions which is error prone, especially when value doesn't have all 16 hex-digits. Consecutive fields can be covered with one macro, e.g. PPC_BITMASK(0,14) in this case.

If that is not possible, please use capital letters for hex values.

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +			err_mask = 0xfff00000; // from Hostboot's log
```suggestion
			err_mask = 0xFFF00000; // from Hostboot's log
```

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	wait_ms(20*TIMEOUT_COUNT,
```suggestion
	wait_ms(PGPE_POLLTIME_MS * TIMEOUT_COUNT,
```

I wonder if we should add a version of wait_ms() to coreboot that checks condition periodically instead of using busy loop. For memory training busy reading significantly slowed down the training. The issue is that we can't use delay() in ramstage, at least not in the same form. Still, this is not part of this task, I'm just thinking out loud :slightly_smiling_face:

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	data |= PPC_PLACE(PBA_OCI_MARKER_BASE >> 16, 18, 3);        // oci_marker_space
Is this correct? PBA_OCI_MARKER_BASE is 0x40070000, it won't fit in just 3 bits. Maybe just set it to 0x7 and skip shifting.

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +static void pba_slave_setup_runtime_phase(void)
This is almost identical to the last lines of pba_reset(), except write gather is disabled for slave 0 there. As SGPE isn't started before pba_slave_setup_runtime_phase() anyway, could you remove lines 790-804? You did much better work describing those registers than me.

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +static void pba_slave_setup_runtime_phase(void)
Also, as these are not documented, please copy the description from comments below to [undocumented_registers.md](https://github.com/3mdeb/openpower-coreboot-docs/blob/main/devnotes/undocumented_registers.md)

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +			*conf_vector |= (0x8000000000000000ull >> pos);
```suggestion
			*conf_vector |= PPC_BIT(pos);
```
Here and below

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	scom_and(PU_SPIPSS_P2S_CTRL_REG0 + 2, ~PPC_BITMASK(0, 16));
Please add comment about which bits are set. Seems that some of them should be set with PPC_PLACE/PPC_SHIFT instead.

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	if ((status & 0xF0) == 0xE0)
Is it even possible? parse_occ_response() checks for OCC_RC_SUCCESS and returns false, so previous `if` will be taken in that case.

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/occ.c
> +		uint32_t spwkup_addr = PPM_SPWKUP_FSP + 0x01000000 * i;
This line is useless, `*_for_chiplet()` functions already add proper offset. Remove it and use `PPM_SPWKUP_FSP` instead of `spwkup_addr`

2021-10-12 08:36 UTC, krystian-hebel commented on src/soc/ibm/power9/occ.c
> +}
Please make those inline and move to ops.h. I can think of at least one use for ppc_mtspr elsewhere.

2021-10-12 08:44 UTC, krystian-hebel commented on src/include/cpu/power/occ.h
> +};
We will have to divide the code even more for upstreaming and probably move the rest of OCC functions to `occ.c`, but for now this should be good enough.

2021-10-12 12:22 UTC, SergiiDmytruk commented on src/soc/ibm/power9/homer.c
> +	data |= PPC_PLACE(PBA_OCI_MARKER_BASE >> 16, 18, 3);        // oci_marker_space
That's how Hostboot does it. I guess `0x40070000` is a final address and `oci_marker_space` is an offset in 64 KiB units from a base address. But yes, it looks too complicated.

2021-10-12 20:34 UTC, SergiiDmytruk commented on src/soc/ibm/power9/homer.c
> +static void pba_slave_setup_runtime_phase(void)
Ended up calling this function once on line 790. Calling it only in `pm_pba_init()` caused hang somewhere in `start_pm_complex()`.

2021-10-19 15:26 UTC, krystian-hebel requested changes
One small change, otherwise LGTM

2021-10-19 15:26 UTC, krystian-hebel commented on src/soc/ibm/power9/fir.c
> +/* SPDX-License-Identifier: GPL-2.0-only */
Almost each component has it's own set of FIR, having this in separate file is misleading. Please move it to occ.c. Same goes for fir.h.

2021-10-19 17:52 UTC, krystian-hebel approved these changes

2021-10-19 17:56 UTC, krystian-hebel commented
Let's wait for CI tests before merging.

2021-10-20 14:53 UTC, merged