Construct MVPD partition in memory on startup
3mdeb/coreboot pull request #102
Opened 2021-09-30 15:56 UTC by SergiiDmytruk

Didn't remove `mvpd_device_init()` and `mvpd_device_ro()` in case it will be needed.

2021-10-12 09:45 UTC, krystian-hebel requested changes

2021-10-12 09:45 UTC, krystian-hebel commented on src/soc/ibm/power9/mvpd.c
> +			kwd_size = small_size;;
```suggestion
			kwd_size = small_size;
```

2021-10-12 09:45 UTC, krystian-hebel commented on src/soc/ibm/power9/mvpd.c
> +		die("Keyword name has wrong length: %s!\n", kwd_name);
Is it always _exactly_ 4 or 2 bytes or can it be less?

2021-10-12 09:45 UTC, krystian-hebel commented on src/soc/ibm/power9/mvpd.c
> +	uint16_t addr = 0xa0;
```suggestion
	uint16_t addr = 0xA0;
```

2021-10-12 09:45 UTC, krystian-hebel commented on src/soc/ibm/power9/mvpd.c
> +#include <device/i2c_simple.h>
This also requires adding `ramstage-y += i2c.c` to Makefile.inc

2021-10-12 14:10 UTC, SergiiDmytruk commented on src/soc/ibm/power9/mvpd.c
> +		die("Keyword name has wrong length: %s!\n", kwd_name);
AFAIK, yes, record and keyword names have fixed length.

2021-10-19 16:01 UTC, krystian-hebel approved these changes
Code for reading MVPD from PNOR stays for now. At some point we will have to test if it's worth to copy data to PNOR after reading, same as Hostboot does it.

2021-10-19 16:01 UTC, merged