Implement block transfer interface of IPMI
3mdeb/coreboot pull request #105
Opened 2021-10-07 20:28 UTC by SergiiDmytruk

As part of `coreboot/src/drivers/ipmi`.

2021-10-19 17:45 UTC, krystian-hebel commented on src/drivers/ipmi/ipmi_kcs.h
> +#include <stdint.h>
There are no changes requiring this include in ipmi_kcs.h, so maybe move it to impmi_if.h

2021-10-19 17:45 UTC, krystian-hebel commented on src/drivers/ipmi/ipmi_bt.c
> +}
Why are those crossed, i.e. first one is generic function name calling BT-specific, and the second the other way around? IMHO we could use just the generic name for both protocols, instead of using wrappers and let the rest for linker - at the moment it is impossible to have both KCS and BT, and I doubt anyone will need both in one FW image. On the other hand, this is something that may have to be revised after review upstream so I won't be forcing any specific approaches, other than keeping the naming scheme consistent.

2021-10-19 17:45 UTC, krystian-hebel commented on src/drivers/ipmi/ipmi_bt.c
> +int ipmi_bt_ignore(uint16_t port)
I think 'clear' or 'reset' would better describe what this function does

2021-10-19 17:45 UTC, krystian-hebel commented on src/drivers/ipmi/Makefile.inc
> +ramstage-$(CONFIG_IPMI_BT_ROMSTAGE) += ipmi_bt.c
```suggestion
romstage-$(CONFIG_IPMI_BT_ROMSTAGE) += ipmi_bt.c
```

2021-10-19 17:45 UTC, krystian-hebel commented on src/soc/ibm/power9/chip.c
> -	 * the payload.
Please leave this comment immediately above activate_slave_cores() so nobody tries to add code after it.

2021-10-19 17:45 UTC, krystian-hebel commented on src/soc/ibm/power9/chip.c
> +	enum { IPMI_BT_PORT_BASE = 0xE4 };
I really don't like the idea of having to hardcode it here. I don't know if coreboot gives a way of getting `dev->path.pnp.port` for arbitrary dev, but even if that isn't possible we can have `extern uint16_t ipmi_port` in ipmi_bt.h and set it in `dev->path.pnp.port()`. Another option is to not pass the port address to `ipmi_bt_ignore()` and have a static global variable for port in ipmi_bt.c instead.

2021-10-19 20:48 UTC, SergiiDmytruk commented on src/drivers/ipmi/ipmi_kcs.h
> +#include <stdint.h>
But there is
```c
void ipmi_bmc_version(uint8_t *ipmi_bmc_major_revision, uint8_t *ipmi_bmc_minor_revision);
```
below from before.

2021-10-19 20:52 UTC, SergiiDmytruk commented on src/soc/ibm/power9/chip.c
> -	 * the payload.
Right, I removed it accidentally during rebase.

2021-10-19 21:15 UTC, SergiiDmytruk commented on src/drivers/ipmi/ipmi_bt.c
> +}
To answer your question, `ipmi_message` and `ipmi_bt_premem_init` are both new functions and they redirect to some other code. But actually I just forgot to look how many times `ipmi_kcs_message` is called and update all the places before dropping thunks...

2021-10-19 21:53 UTC, SergiiDmytruk commented on src/soc/ibm/power9/chip.c
> +	enum { IPMI_BT_PORT_BASE = 0xE4 };
There is a list of all devices, however identification is done by comparing `chip_ops->name`, because I didn't find anything better.

2021-10-20 12:55 UTC, krystian-hebel commented on src/drivers/ipmi/ipmi_kcs.h
> +#include <stdint.h>
Ok, so that is an issue in the current code I guess, let's leave it then.

2021-10-20 13:05 UTC, krystian-hebel commented on src/soc/ibm/power9/chip.c
> +	enum { IPMI_BT_PORT_BASE = 0xE4 };
Looks good, but please add check for `dev->chip_ops->initialized` and `dev->enabled`, just in case.

2021-10-21 12:13 UTC, macpijan commented
@SergiiDmytruk All review comments seems to be resolved. One conflict appeared. Please resolve that.

2021-10-21 14:26 UTC, SergiiDmytruk commented
@macpijan PR wasn't approved, @krystian-hebel probably haven't tested latest changes yet.

2021-10-21 17:58 UTC, krystian-hebel requested changes
Either change as in suggestions or reverse return values for bt_clear and change the condition checked in chip.c

2021-10-21 17:58 UTC, krystian-hebel commented on src/drivers/ipmi/ipmi_bt_ops.c
> +	if (!ipmi_bt_clear(dev->path.pnp.port))
```suggestion
	if (ipmi_bt_clear(dev->path.pnp.port))
```

2021-10-21 17:58 UTC, krystian-hebel commented on src/drivers/ipmi/ipmi_ops_premem.c
> +	if (!ipmi_bt_clear(dev->path.pnp.port))
```suggestion
	if (ipmi_bt_clear(dev->path.pnp.port))
```

2021-10-22 09:25 UTC, krystian-hebel approved these changes

2021-10-22 09:29 UTC, krystian-hebel commented
I am doing rebase and merge because commits are already nicely split for upstreaming.

2021-10-22 09:29 UTC, merged