soc/power9: implement istep 13.4
3mdeb/coreboot pull request #35
Opened 2021-02-24 15:05 UTC by krystian-hebel

Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>

2021-03-26 14:33 UTC, miczyg1 requested changes

2021-03-26 14:33 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_4.c
> +		write_scom_for_chiplet(mcs_ids[i], 0x070F0045, ~PPC_BIT(2));
Preprocessor definitions of registers and bits

2021-03-26 14:33 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_4.c
> +		// > end if
But there is no IF begginning

2021-03-26 14:35 UTC, krystian-hebel commented on src/soc/ibm/power9/istep_13_4.c
> +		// > end if
Line 66

2021-05-13 09:32 UTC, macpijan commented
Already integrated in: https://github.com/3mdeb/coreboot/pull/49

2021-05-13 09:32 UTC, closed without merging