WIP: soc/power9: implement istep 13.6
3mdeb/coreboot pull request #38
Opened 2021-02-26 15:47 UTC by krystian-hebel

Signed-off-by: Krystian Hebel <krystian.hebel@3mdeb.com>

2021-04-15 10:38 UTC, miczyg1 requested changes

2021-04-15 10:38 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_6.c
> +	write_scom_for_chiplet(id, 0x07000021, ~ATTR_PG & PPC_BITMASK(3,14));
Register definitions in preprocessor along with bits

2021-04-15 10:38 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_6.c
> +	if (!wait_us(10 * 100, read_scom_for_chiplet(id, 0x07000100) & PPC_BIT(9)))
I see the delay of 100000ns which is 100us, so why 10*100us?

2021-04-15 10:38 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_6.c
> +	if (!wait_us(10 * 100, read_scom_for_chiplet(id, 0x07000100) & PPC_BIT(8)))
Same as above with timeout

2021-04-15 10:38 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_6.c
> +	// reset pervasive FIR
How do we know which l_unit_idx is this?

2021-04-15 10:38 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_6.c
> +		    dimms[i].ecc_extension == true) {
So the DIMMs must have ECC in order to work?

2021-05-13 09:32 UTC, macpijan commented
Already integrated in: https://github.com/3mdeb/coreboot/pull/49

2021-05-13 09:32 UTC, closed without merging