Istep 13 8
3mdeb/coreboot pull request #40
Opened 2021-03-04 17:31 UTC by krystian-hebel

2021-03-25 10:02 UTC, macpijan commented
@miczyg1 Please review

2021-04-15 10:52 UTC, miczyg1 requested changes

2021-04-15 10:52 UTC, miczyg1 commented on src/mainboard/raptor-cs/talos-2/romstage.c
> +			}
The code from lines 209 to 300 could be a function. This kind of nested level is hard to follow when a for loop is so long

2021-05-13 09:32 UTC, macpijan commented
Already integrated in: https://github.com/3mdeb/coreboot/pull/49

2021-05-13 09:32 UTC, closed without merging