WIP: Istep 13 9
3mdeb/coreboot pull request #41
Opened 2021-03-17 19:15 UTC by krystian-hebel

2021-03-25 10:03 UTC, macpijan commented
@miczyg1 please review

2021-04-15 12:03 UTC, miczyg1 requested changes

2021-04-15 12:03 UTC, miczyg1 commented on src/include/cpu/power/istep_13.h
> +	return 1000000 / (mem_data.speed / 2);
```suggestion
	return PSEC_PER_USEC / (mem_data.speed / 2);
```

We define a value but do not use it? Or is it something different?

2021-04-15 12:03 UTC, miczyg1 commented on src/include/cpu/power/istep_13.h
> +	return ((ps * 1000 / tck_in_ps()) + 974) / 1000;
```suggestion
	return ((ps * PSEC_PER_NSEC / tck_in_ps()) + 974) / PSEC_PER_NSEC;
```

Applicable or not?

2021-04-15 12:03 UTC, miczyg1 commented on src/include/cpu/power/istep_13.h
> +	mca_and_or(mcs, mca, scom + dp * 0x40000000000, and, or);
`dp` could be bit-shifted? Multiplying by a big hex value like this is weird. What is the exact meaning of this multiplication?

2021-04-15 12:03 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_9.c
> +	uint64_t status = mca_read(id, mca_i, 0x8000C0000701103F);
Please use the preprocessor to define register names, using hardcoded values is ugly.

2021-04-15 12:03 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_9.c
> +	if ((status & PPC_BITMASK(48, 53)) == (PPC_BIT(48) | PPC_BIT(51))) {
You may pass the status to a simple function that checks for good bits. These bits can have their names too in preprocessor or something.

2021-04-15 12:03 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_9.c
> +	if (status & (PPC_BIT(49) | PPC_BIT(50) | PPC_BIT(52) | PPC_BIT(53))) {
Same here, the function could check for error bits

2021-04-15 12:03 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_9.c
> +		/* FIXME: how is PHY numbering related to MCA numbering? mca_i/2? */
Maybe a good question to mailing list?

2021-04-15 12:03 UTC, miczyg1 commented on src/soc/ibm/power9/istep_13_9.c
> + * which it is invoked. As a side effect, it is used without semicolon.
"If only not the IF" and the braces, it could end with semicolon

2021-05-13 09:32 UTC, macpijan commented
Already integrated in: https://github.com/3mdeb/coreboot/pull/49

2021-05-13 09:32 UTC, closed without merging