Istep 13 10
3mdeb/coreboot pull request #44
Opened 2021-03-25 14:26 UTC by krystian-hebel

2021-04-15 13:35 UTC, miczyg1 requested changes

2021-04-15 13:35 UTC, miczyg1 commented on src/device/dram/rcd.c
> +	i2c_transfer(bus, seg, 1);
No checks for transfer status?

2021-04-15 13:35 UTC, miczyg1 commented on src/soc/ibm/power9/ccs.c
> +	write_scom_for_chiplet(id, 0x07012315 + instr,
Lets change the hardcodes to names with preprocessor

2021-05-13 09:31 UTC, macpijan commented
Already integrated in: https://github.com/3mdeb/coreboot/pull/49

2021-05-13 09:31 UTC, closed without merging