Layout CME and SGPE rings in HOMER image
3mdeb/coreboot pull request #86
Opened 2021-08-22 22:40 UTC by SergiiDmytruk

2021-08-24 12:10 UTC, krystian-hebel requested changes

2021-08-24 12:10 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +#define CORE0_CHIPLET_ID  0x20
We have `EP00_CHIPLET_ID` and `EC00_CHIPLET_ID` in scom.h, use them instead.

2021-08-24 12:10 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +};
Most of the above (if not all) is in files added by `pstates` branch, so either a rebase or another fix after merging both into `homer` will be needed.

2021-08-24 12:10 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +	ring_variant = (dd < 23 ? RV_BASE : RV_RL4);
```suggestion
	ring_variant = (dd < 0x23 ? RV_BASE : RV_RL4);
```

2021-08-24 12:10 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +			uint8_t chiplet_id = CACHE0_CHIPLET_ID + quad*2;
Please either change that variable name or add a comment that this is **not** an SCOM chiplet ID, or both. I know it is called like that in Hostboot, but it is misleading - there are only 6 cache chiplets.

2021-08-24 12:10 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +			if (i != 0 && (i - 1) % 2 == 1)
Simpler:
```suggestion
			if (i != 0 && (i % 2) == 0)
```
Sidenote: Hostboot has an original idea of odd/even numbers :slightly_smiling_face:

2021-08-24 15:47 UTC, SergiiDmytruk commented on src/soc/ibm/power9/homer.c
> +};
I saw those files, but thought they were added as-is temporarily.

2021-08-31 11:15 UTC, krystian-hebel approved these changes
Code looks good and gives exactly the same result as Hostboot. The only thing I'm concerned about is `ALIGN_UP(payload - start, 8)` when `start` isn't already aligned, but the logic is identical to Hostboot so let's leave it as it is.

2021-08-31 11:17 UTC, merged

2021-08-31 11:20 UTC, krystian-hebel commented on src/soc/ibm/power9/homer.c
> +};
That was my initial idea, but Pstate's code uses most of those anyway so I think adding whole files (and not taking the responsibility for misleading field names :slightly_smiling_face: ) will be better.